### ISSUE TITLE
test rultor

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#1]
@rultor hello

**Comment by 0pdd** [comment]
@ammaratef45 the puzzle [#3](https://github.com/ammaratef45/zold-flutter-client/issues/3) is still not solved.

**Comment by 0pdd** [comment]
@ammaratef45 the only puzzle [#3](https://github.com/ammaratef45/zold-flutter-client/issues/3) is solved here.
