### ISSUE TITLE
Deployment of iOS

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#10]
Need help with the deploying iOS apps with rultor (or any alternatives)
This is supposed to be done using fastlane

**Comment by amorenew** [comment]
@ammaratef45 Zold Logo SVG
http://www.zold.io/images/logo.svg
![logo512](https://user-images.githubusercontent.com/2842459/53302484-ea9e0900-3877-11e9-99ed-d0a10fa00384.png)
![logo1024](https://user-images.githubusercontent.com/2842459/53302485-ea9e0900-3877-11e9-824f-cd1b058f997f.png)
