### ISSUE TITLE
Buttons refactory

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#100]
A puzzle for #99
We should use a custom button widget that has the default style and reuses it everywhere.

The task is to create a widget for the custom button and let it have a default style then replace all Buttons with it

**Comment by ammaratef45** [comment]
@amorenew do you want to take this?

**Comment by 0crat** [comment]
Job [#100](https://github.com/ammaratef45/zold-flutter-client/issues/100) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#100](https://github.com/ammaratef45/zold-flutter-client/issues/100); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by amorenew** [comment]
@ammaratef45 Yes I could take it.
Thanks

**Comment by ammaratef45** [comment]
@0crat assign @amorenew

**Comment by 0crat** [comment]
> @0crat assign @amorenew  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/100#issuecomment-494632483))

@ammaratef45 The job [#100](https://github.com/ammaratef45/zold-flutter-client/issues/100) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/e0a5d68a-aa1c-47b4-994d-ec1da9509eea); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @amorenew[/z](https://www.0crat.com/u/amorenew) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by amorenew** [comment]
@ammaratef45 should be closed as it is already merged

**Comment by ammaratef45** [comment]
@amorenew thanks

**Comment by 0crat** [comment]
Job [#100](https://github.com/ammaratef45/zold-flutter-client/issues/100) is not in the agenda of @amorenew[/z](https://www.0crat.com/u/amorenew), can't retrieve data and time of add

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @amorenew[/z](https://www.0crat.com/u/amorenew), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#100](https://github.com/ammaratef45/zold-flutter-client/issues/100) is not in the agenda of @amorenew[/z](https://www.0crat.com/u/amorenew), can't inspect

**Comment by 0crat** [comment]
The job [#100](https://github.com/ammaratef45/zold-flutter-client/issues/100) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
