### ISSUE TITLE
Add some titles

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#101]
Puzzle for #99 

Add a title to the "pay" page: "Send ZLD"

Add a title to the "invoice" page: "Create Invoice"

**Comment by ammaratef45** [comment]
@amorenew I can assign this to you if you would like to implement it

**Comment by amorenew** [comment]
@ammaratef45 yes assign it.

**Comment by ammaratef45** [comment]
@0crat assign @amorenew

**Comment by 0crat** [comment]
> @0crat assign @amorenew  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/101#issuecomment-494632416))

@ammaratef45 The job [#101](https://github.com/ammaratef45/zold-flutter-client/issues/101) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/f16bb573-1b3d-46ca-8ca6-d032692ca81d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @amorenew[/z](https://www.0crat.com/u/amorenew) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by amorenew** [comment]
@ammaratef45 why 0crat did not assign it.. check assignees section

**Comment by ammaratef45** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/ammaratef45/zold-flutter-client/issues/101#issuecomment-494668899))

@ammaratef45 This is what I know about this job in [CGC59KB9B](https://www.0crat.com/p/CGC59KB9B), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#101](https://github.com/ammaratef45/zold-flutter-client/issues/101) is [in scope](http://www.zerocracy.com/policy.html#14) for 3hr
  * The role is `DEV`
  * The job is assigned to @amorenew[/z](https://www.0crat.com/u/amorenew) for [3hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @ammaratef45[/z](https://www.0crat.com/u/ammaratef45): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CGC59KB9B?q=%7Bjob%3A%27gh%3Aammaratef45%2Fzold-flutter-client%23101%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ammaratef45** [comment]
@amorenew You'll be able to see it in your [agenda](https://www.0crat.com/u/amorenew/agenda)

**Comment by amorenew** [comment]
is it a bug I tried to filter issues by assignee but not working?
should we report it? @ammaratef45 
I talk about github itself

**Comment by ammaratef45** [comment]
@amorenew your account isn't visible in the list of accounts I can assign the issue to,
I think zerocrat tried to assign you and failed.

I will search for information about this

**Comment by amorenew** [comment]
@ammaratef45 should be closed as it is already merged

**Comment by 0crat** [comment]
Job [#101](https://github.com/ammaratef45/zold-flutter-client/issues/101) is not in the agenda of @amorenew[/z](https://www.0crat.com/u/amorenew), can't retrieve data and time of add

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @amorenew[/z](https://www.0crat.com/u/amorenew), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#101](https://github.com/ammaratef45/zold-flutter-client/issues/101) is not in the agenda of @amorenew[/z](https://www.0crat.com/u/amorenew), can't inspect

**Comment by 0crat** [comment]
The job [#101](https://github.com/ammaratef45/zold-flutter-client/issues/101) is now out of scope

**Comment by sereshqua** [comment]
@ammaratef45 please make sure that messages in a job always start with a name of a user they are addressed to; as in [policy](http://www.zerocracy.com/policy.html#30)

**Comment by ammaratef45** [comment]
@sereshqua you mean @amorenew?

**Comment by sereshqua** [comment]
@ammaratef45 i am sorry, i was meaning to tag @amorenew

**Comment by amorenew** [comment]
@sereshqua Ok sure I will remember that

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
