### ISSUE TITLE
Full design by Adobe XD

### ISSUE THREAD

**Issue by amorenew** [ammaratef45/zold-flutter-client#102]
I wonder if we could make the app designed fully by Adobe XD then we implement it.
First, we could start by Login and Verification page then once we get approval on our design we go ahead on implementing it.
@ammaratef45 @yegor256 
Could check my redesign of the Login page by Adobe XD?
If you like it then I will redesign all pages by Adobe XD. 
![image](https://user-images.githubusercontent.com/2842459/58145862-0ab14e80-7c54-11e9-9410-1259b7d14ce1.png)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ammaratef45** [comment]
@amorenew let's discuss this matter in Telegram and open tickets with the final approved design.
It's awesome that you know how to use Adobe XD 👍

**Comment by yegor256** [comment]
@amorenew @ammaratef45 I would suggest staying as close to Flutter defaults as possible. Don't change their fonts, their colors, their default layouts. This is how the app will look _consistent_.

**Comment by amorenew** [comment]
@amorenew Flutter is not a design system by itself it just a CSS and styles.
So for having consistent, we should have a pdf design otherwise over the time consistency will get out of our hand.
There is an Egyptian group for studying Flutter I can invite them but without a pdf design "documentation" it will be hard to guide them.

**Comment by ammaratef45** [comment]
@amorenew let's concentrate on finalizing the UI tweaks for now.

**Comment by amorenew** [comment]
Updates:
_____________________________________________________________
![iPhone X-XS – 1@2x](https://user-images.githubusercontent.com/2842459/58307955-7d5f2d00-7e00-11e9-8db2-94305c34dd76.png)
_____________________________________________________________
![iPhone X-XS – 2@2x](https://user-images.githubusercontent.com/2842459/58307956-7d5f2d00-7e00-11e9-990a-ec2f2e962df4.png)
_____________________________________________________________
![iPhone X-XS – 3@2x](https://user-images.githubusercontent.com/2842459/58307957-7d5f2d00-7e00-11e9-827a-6bb0d0832c24.png)
_____________________________________________________________
![iPhone X-XS – 4@2x](https://user-images.githubusercontent.com/2842459/58307958-7df7c380-7e00-11e9-88ba-399e17e45731.png)

**Comment by amorenew** [comment]
I will close this issue because I want the list of issues should be clean.
I will open an issue for every screen

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#102` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
