### ISSUE TITLE
More details

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#104]
Puzzle for #99 

Add more details to the main screen with the list of transactions: 1) how many transactions in the wallet, 2) size of the wallet, 3) taxes (you can find this information in the main page of WTS)

**Comment by 0crat** [comment]
Job [#104](https://github.com/ammaratef45/zold-flutter-client/issues/104) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#104](https://github.com/ammaratef45/zold-flutter-client/issues/104); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#104](https://github.com/ammaratef45/zold-flutter-client/issues/104) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/5afa8a19-4735-43ee-acee-6d63f2504451); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@amorenew are you willing to work on this?

**Comment by amorenew** [comment]
@ammaratef45 I am not familiar with The API yet I will keep working on the UI

**Comment by ammaratef45** [comment]
@0crat unassign

**Comment by 0crat** [comment]
> @0crat unassign ([here](https://github.com/ammaratef45/zold-flutter-client/issues/104#issuecomment-498136642))

@ammaratef45 Can't understand "unassign", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by ammaratef45** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/ammaratef45/zold-flutter-client/issues/104#issuecomment-498136953))

@ammaratef45 The user @amorenew[/z](https://www.0crat.com/u/amorenew) resigned from [#104](https://github.com/ammaratef45/zold-flutter-client/issues/104), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#104](https://github.com/ammaratef45/zold-flutter-client/issues/104) assigned to @nermeen78[/z](https://www.0crat.com/u/nermeen78), here is [why](https://www.0crat.com/footprint/CGC59KB9B/0611212d-6010-4404-90ae-939c19eef774); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c6675062-cc84-4507-ab95-22913e5b7093, thread: pool-19-thread-3
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.2' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.5](https://github.com/zerocracy/farm): CID: [b6cdf76e-8be4-43da-808b-612a61ebed80](https://www.0crat.com/footprint/CGC59KB9B/b6cdf76e-8be4-43da-808b-612a61ebed80), Type: "Job milestoned"

**Comment by 0crat** [comment]
@nermeen78[/z](https://www.0crat.com/u/nermeen78) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@Nermeen78 I can assign myself here if you don't have enough time for it.
No push on you, I'm just offering help.

**Comment by Nermeen78** [comment]
@ammaratef45 please do this

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) I see that you unassigned this issue; the order is still assigned to @nermeen78[/z](https://www.0crat.com/u/nermeen78) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#104](https://github.com/ammaratef45/zold-flutter-client/issues/104) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/07936a54-97bc-4757-a9a9-d638090dd447); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@0crat wait for response on zold-io/wts.zold.io#264

**Comment by 0crat** [comment]
> @0crat wait for response on zold-io/wts.zold.io#264 ([here](https://github.com/ammaratef45/zold-flutter-client/issues/104#issuecomment-502572891))

@ammaratef45 The impediment for [#104](https://github.com/ammaratef45/zold-flutter-client/issues/104) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#104](https://github.com/ammaratef45/zold-flutter-client/issues/104) is now out of scope

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d187b2ba-a3c0-4736-9c6e-4a20e5597990, thread: pool-7-thread-5
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.2/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.6](https://github.com/zerocracy/farm): CID: [4ba68c5f-a105-41c4-aef1-5f22b137d466](https://www.0crat.com/footprint/CGC59KB9B/4ba68c5f-a105-41c4-aef1-5f22b137d466), Type: "Transfer shares"

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
