### ISSUE TITLE
Adding Visual Studio Code configurations

### ISSUE THREAD

**Issue by amorenew** [ammaratef45/zold-flutter-client#105]
For easy debugging, I wonder if we could have Visual Studio Code configurations so the contributors who don't want to use terminal for running emulator or launching the app could easily use the debugging toolbar on VSC
Configuration should do:
1-When click  Start debugging from debug menu we should see a list of emulator devices
2-When once debugging started we could have a toolbar for reloading or step debugging on break points.
3-When we save any file it should be auto formatted.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amorenew** [comment]
It will allow format on save so the commit will be with the formatted code.

**Comment by ammaratef45** [comment]
@amorenew Thanks, terminal guys like me are too lazy to configure IDEs

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#105` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
