### ISSUE TITLE
App should work in debug mode even in emulator

### ISSUE THREAD

**Issue by amorenew** [ammaratef45/zold-flutter-client#107]
**Describe the bug**
The app showing a warning page while debugging

**To Reproduce**
1. Just open the app

**Expected behavior**
The app should work in debugging mode without warning page

**Additional context**
We could use this flag for debugging mode https://api.flutter.dev/flutter/foundation/kReleaseMode-constant.html

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#107](https://github.com/ammaratef45/zold-flutter-client/issues/107) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by ammaratef45** [comment]
@amorenew Thanks

**Comment by 0crat** [comment]
The job [#107](https://github.com/ammaratef45/zold-flutter-client/issues/107) is now out of scope

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#107` is not assigned, can't get performer
