### ISSUE TITLE
Redesign Login page

### ISSUE THREAD

**Issue by amorenew** [ammaratef45/zold-flutter-client#108]
Redesign the Login page like the following design

The acceptance criteria:

- [x] 1. Use Text form field widget to show error on the invalid phone number otherwise, the user will get a wrong error message when the API gets called.
- [ ] 2. Use the general theme of the app.
- [ ] 3. Show a circular spinner instead of the send button in case of API is called
- [ ] 4. On Android fill mobile number automatically 
- [x] 5. Tap outside mobile field should hide the keyboard
- [x] 6. Show login instead of Enter key on the keyboard and link it to login function
 
![iPhone X-XS – 2](https://user-images.githubusercontent.com/2842459/58375998-9252d200-7f60-11e9-8ca2-8288f87dd9e3.png)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ammaratef45** [comment]
@amorenew do you want to implement the new design?

**Comment by amorenew** [comment]
@ammaratef45 you can take it if you want

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@62637b42-8780-4988-af20-1984572b8182, thread: pool-5-thread-2
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.1' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.3](https://github.com/zerocracy/farm): CID: [d7668c3e-5332-4b48-9b98-37c17b60ff42](https://www.0crat.com/footprint/CGC59KB9B/d7668c3e-5332-4b48-9b98-37c17b60ff42), Type: "Job milestoned"

**Comment by ammaratef45** [comment]
@0crat assign @amorenew

**Comment by 0crat** [comment]
> @0crat assign @amorenew  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/108#issuecomment-500106025))

@ammaratef45 The job [#108](https://github.com/ammaratef45/zold-flutter-client/issues/108) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/b786a4d1-1897-4615-9bd3-744a22a2209e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @amorenew[/z](https://www.0crat.com/u/amorenew), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#108](https://github.com/ammaratef45/zold-flutter-client/issues/108) is not in the agenda of @amorenew[/z](https://www.0crat.com/u/amorenew), can't inspect

**Comment by 0crat** [comment]
The job [#108](https://github.com/ammaratef45/zold-flutter-client/issues/108) is now out of scope

**Comment by sereshqua** [comment]
@ammaratef45 @amorenew please make sure that problem reporter and problem solver are two different persons

**Comment by ammaratef45** [comment]
@sereshqua I don't have enough DEVs for this rule, I will try to avoid that next time

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +35 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/ammaratef45/zold-flutter-client/issues/108#issuecomment-544453249))

@g4s8 This is what I know about this job in [CGC59KB9B](https://www.0crat.com/p/CGC59KB9B), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#108](https://github.com/ammaratef45/zold-flutter-client/issues/108) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CGC59KB9B?q=%7Bjob%3A%27gh%3Aammaratef45%2Fzold-flutter-client%23108%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
