### ISSUE TITLE
Need High-res icon and cover Image

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#11]
Needed 512x512 image as a profile image of the store app
Also 1024x500 image as a cover image

**Comment by amorenew** [comment]
@ammaratef45 Zold Logo SVG
http://www.zold.io/images/logo.svg
![logo512](https://user-images.githubusercontent.com/2842459/53302484-ea9e0900-3877-11e9-99ed-d0a10fa00384.png)
![logo1024](https://user-images.githubusercontent.com/2842459/53302485-ea9e0900-3877-11e9-824f-cd1b058f997f.png)

**Comment by ammaratef45** [comment]
@amorenew Can you adjust the second one dimensions? It should be 1024x500

**Comment by amrboxit4me** [comment]
@ammaratef45 
Same like website blue #205995
https://www.zold.io/images/logo-blue.svg
![untitled-1](https://user-images.githubusercontent.com/41638061/53316026-9fb7dc00-38df-11e9-972a-e302114c18e4.png)

**Comment by ammaratef45** [comment]
@amorenew Thank you :+1:
