### ISSUE TITLE
Get rid of texts inside the form fields

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#111]
Instead, make labels before each field. Just like it's done in this page: https://wts.zold.io/pay

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#111](https://github.com/ammaratef45/zold-flutter-client/issues/111) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#111](https://github.com/ammaratef45/zold-flutter-client/issues/111) assigned to @nermeen78[/z](https://www.0crat.com/u/nermeen78), here is [why](https://www.0crat.com/footprint/CGC59KB9B/1d035895-31d3-4cc1-9124-7a61aa4cacb1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@nermeen78[/z](https://www.0crat.com/u/nermeen78) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c6675062-cc84-4507-ab95-22913e5b7093, thread: pool-19-thread-7
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.2' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.5](https://github.com/zerocracy/farm): CID: [df9d01dc-d842-40bf-a964-fe05bab6db35](https://www.0crat.com/footprint/CGC59KB9B/df9d01dc-d842-40bf-a964-fe05bab6db35), Type: "Job milestoned"

**Comment by Nermeen78** [comment]
@0crat wait for merge and review

**Comment by 0crat** [comment]
> @0crat wait for merge and review ([here](https://github.com/ammaratef45/zold-flutter-client/issues/111#issuecomment-501514599))

@Nermeen78 The impediment for [#111](https://github.com/ammaratef45/zold-flutter-client/issues/111) was registered successfully by @nermeen78[/z](https://www.0crat.com/u/nermeen78)

**Comment by 0crat** [comment]
Job [#111](https://github.com/ammaratef45/zold-flutter-client/issues/111) is not in the agenda of @nermeen78[/z](https://www.0crat.com/u/nermeen78), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @nermeen78[/z](https://www.0crat.com/u/nermeen78), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#111](https://github.com/ammaratef45/zold-flutter-client/issues/111) is now out of scope

**Comment by sereshqua** [comment]
@Nermeen78 please make sure, that ticket has references to all pull requests (provide by you, not code reviewer) where the problem was actually fixed

**Comment by sereshqua** [comment]
@Nermeen78 ping

**Comment by Nermeen78** [comment]
@sereshqua  Ok I will make sure to add references in the ticket for its related pull request but this issue was already closed.

**Comment by sereshqua** [comment]
@Nermeen78 i am not saying about this particular, i just warn you to avoid problem in future :)

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by Nermeen78** [comment]
@sereshqua thanks :)

**Comment by 0crat** [comment]
> @0crat quality acceptable  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/111#issuecomment-502357787))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@94e41765-2124-4e0a-9ff5-7c3ef2c1c8f0, thread: pool-8-thread-8
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.5](https://github.com/zerocracy/farm): CID: [fb095154-b0f1-4362-b43d-0e7ea4f06d3d](https://www.0crat.com/footprint/CGC59KB9B/fb095154-b0f1-4362-b43d-0e7ea4f06d3d), Type: "Transfer shares"

**Comment by 0crat** [comment]
> @0crat quality acceptable  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/111#issuecomment-502357787))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@94e41765-2124-4e0a-9ff5-7c3ef2c1c8f0, thread: pool-8-thread-1
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.5](https://github.com/zerocracy/farm): CID: [53d71d48-3677-41ae-ba81-0dbe538ed481](https://www.0crat.com/footprint/CGC59KB9B/53d71d48-3677-41ae-ba81-0dbe538ed481), Type: "Transfer shares"

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @nermeen78[/z](https://www.0crat.com/u/nermeen78)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
