### ISSUE TITLE
Make all buttons the same style

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#112]
Why "login" button and "pay" button look differently?

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#112](https://github.com/ammaratef45/zold-flutter-client/issues/112) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/9e9a4ebd-92b7-496b-b684-82265a09e379); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c6675062-cc84-4507-ab95-22913e5b7093, thread: pool-19-thread-5
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.2' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.5](https://github.com/zerocracy/farm): CID: [f79cecc1-f1a3-4681-a591-fa37d78ee1e5](https://www.0crat.com/footprint/CGC59KB9B/f79cecc1-f1a3-4681-a591-fa37d78ee1e5), Type: "Job milestoned"

**Comment by ammaratef45** [comment]
@yegor256 @amorenew This is deprecated because of the redesign now

**Comment by ammaratef45** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/ammaratef45/zold-flutter-client/issues/112#issuecomment-500208876))

@ammaratef45 The user @amorenew[/z](https://www.0crat.com/u/amorenew) resigned from [#112](https://github.com/ammaratef45/zold-flutter-client/issues/112), please stop working. Reason for job resignation: Order was cancelled

**Comment by ammaratef45** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/ammaratef45/zold-flutter-client/issues/112#issuecomment-500209457))

@ammaratef45 Job `gh:ammaratef45/zold-flutter-client#112` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/ammaratef45/zold-flutter-client/issues/112#issuecomment-500209457))

@ammaratef45 The job [#112](https://github.com/ammaratef45/zold-flutter-client/issues/112) is now out of scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/ammaratef45/zold-flutter-client/issues/112#issuecomment-500209457))

@ammaratef45 @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#112](https://github.com/ammaratef45/zold-flutter-client/issues/112), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#112](https://github.com/ammaratef45/zold-flutter-client/issues/112) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/9501f2e0-461d-4a2d-a7fe-c0f59a41efe0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/ammaratef45/zold-flutter-client/issues/112#issuecomment-500209562))

@ammaratef45 This is what I know about this job in [CGC59KB9B](https://www.0crat.com/p/CGC59KB9B), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#112](https://github.com/ammaratef45/zold-flutter-client/issues/112) is not in scope
  * These users are banned and won't be assigned:
    * @ammaratef45[/z](https://www.0crat.com/u/ammaratef45): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CGC59KB9B?q=%7Bjob%3A%27gh%3Aammaratef45%2Fzold-flutter-client%23112%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#112` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
