### ISSUE TITLE
We need to migrate to AndroidX

### ISSUE THREAD

**Issue by amorenew** [ammaratef45/zold-flutter-client#115]
Barcode scan library made a problem to me because it has a major release with AndroidX so I think we should consider updating all plugins to a major release which support AndroidX
Other than that if the plugin does not supports AndroidX we have to make a pull request or forking it.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@70f18830-1e89-4796-9392-73b08f925466, thread: pool-14-thread-7
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.2' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.5](https://github.com/zerocracy/farm): CID: [f171ff29-8aad-4978-aaf0-00b68ff3346e](https://www.0crat.com/footprint/CGC59KB9B/f171ff29-8aad-4978-aaf0-00b68ff3346e), Type: "Job milestoned"

**Comment by ammaratef45** [comment]
@amorenew That was on my mind, We should take care of this

**Comment by 0crat** [comment]
Job [#115](https://github.com/ammaratef45/zold-flutter-client/issues/115) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
The job [#115](https://github.com/ammaratef45/zold-flutter-client/issues/115) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/e27c88e4-1c61-41e9-ba9f-23972def1886); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@amorenew please check if any build fails because of AndroidX now

**Comment by amorenew** [comment]
@ammaratef45 no issue the project is building and run usefully

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#115](https://github.com/ammaratef45/zold-flutter-client/issues/115) is now out of scope
