### ISSUE TITLE
Use Flutter-Mobile-Number-Plugin to try to get the number automatically

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#117]
[This](https://github.com/amorenew/Flutter-Mobile-Number-Plugin) project can allow getting the mobile number automatically in Android.

The task is to use it and try to fill the number field with the number of the SIM on the phone.

**Comment by 0crat** [comment]
Job [#117](https://github.com/ammaratef45/zold-flutter-client/issues/117) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c6675062-cc84-4507-ab95-22913e5b7093, thread: pool-19-thread-1
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.2' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.5](https://github.com/zerocracy/farm): CID: [b1bfcd8e-2a29-4787-a313-295902b6a6fd](https://www.0crat.com/footprint/CGC59KB9B/b1bfcd8e-2a29-4787-a313-295902b6a6fd), Type: "Job milestoned"

**Comment by amorenew** [comment]
@ammaratef45 I want to take this issue

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#117](https://github.com/ammaratef45/zold-flutter-client/issues/117) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/2ae3fc83-36da-4d98-8b49-514ea0200312); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amorenew** [comment]
@ammaratef45 I resolved this issue

**Comment by ammaratef45** [comment]
@amorenew Thanks, It's under review now, put the issue on the wait

**Comment by ammaratef45** [comment]
@amorenew Thanks

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @amorenew[/z](https://www.0crat.com/u/amorenew), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#117](https://github.com/ammaratef45/zold-flutter-client/issues/117) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/117#issuecomment-503046767))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d187b2ba-a3c0-4736-9c6e-4a20e5597990, thread: pool-7-thread-7
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.2/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.6](https://github.com/zerocracy/farm): CID: [6540769e-38f8-4980-984a-8dec207d9080](https://www.0crat.com/footprint/CGC59KB9B/6540769e-38f8-4980-984a-8dec207d9080), Type: "Transfer shares"

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
> @0crat quality good  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/117#issuecomment-503046767))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d187b2ba-a3c0-4736-9c6e-4a20e5597990, thread: pool-7-thread-4
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.2/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.6](https://github.com/zerocracy/farm): CID: [afb01b61-58aa-4a9a-8a32-78ff70cf1fc3](https://www.0crat.com/footprint/CGC59KB9B/afb01b61-58aa-4a9a-8a32-78ff70cf1fc3), Type: "Transfer shares"

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
