### ISSUE TITLE
Redesign home page

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#118]
Make a new design in Adobe XD for the home page

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c6675062-cc84-4507-ab95-22913e5b7093, thread: pool-19-thread-7
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.3' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.5](https://github.com/zerocracy/farm): CID: [d448c958-1167-4723-b057-0181a04e1a86](https://www.0crat.com/footprint/CGC59KB9B/d448c958-1167-4723-b057-0181a04e1a86), Type: "Job milestoned"

**Comment by 0crat** [comment]
The job [#118](https://github.com/ammaratef45/zold-flutter-client/issues/118) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/318f0588-70c7-45b0-924b-34bb7613ffe5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d187b2ba-a3c0-4736-9c6e-4a20e5597990, thread: pool-7-thread-6
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.2/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.6](https://github.com/zerocracy/farm): CID: [382af25a-38e7-456b-a9d8-c8e5eef5ae0c](https://www.0crat.com/footprint/CGC59KB9B/382af25a-38e7-456b-a9d8-c8e5eef5ae0c), Type: "Transfer shares"

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amorenew** [comment]
@0crat \wait

**Comment by 0crat** [comment]
> @0crat \wait ([here](https://github.com/ammaratef45/zold-flutter-client/issues/118#issuecomment-504866965))

@amorenew Can't understand "\wait", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by amorenew** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/ammaratef45/zold-flutter-client/issues/118#issuecomment-504867218))

@amorenew The impediment for [#118](https://github.com/ammaratef45/zold-flutter-client/issues/118) was registered successfully by @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by amorenew** [comment]
New design
![Design Guidelines@3x](https://user-images.githubusercontent.com/2842459/60860711-ccceb080-a228-11e9-8cbf-85c461dcce41.png)

![Dashboard@3x](https://user-images.githubusercontent.com/2842459/60860710-ccceb080-a228-11e9-94ee-cb57fde5dc7c.png)

**Comment by ammaratef45** [comment]
@amorenew Thanks

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @amorenew[/z](https://www.0crat.com/u/amorenew), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#118](https://github.com/ammaratef45/zold-flutter-client/issues/118) is now out of scope

**Comment by 0crat** [comment]
Job [#118](https://github.com/ammaratef45/zold-flutter-client/issues/118) is not in the agenda of @amorenew[/z](https://www.0crat.com/u/amorenew), can't inspect

**Comment by sereshqua** [comment]
@amorenew please make sure you always start your messages with the name of the user they are addressed to, [see](https://github.com/ammaratef45/zold-flutter-client/issues/118#issuecomment-509489767)

**Comment by amorenew** [comment]
@sereshqua Ok sure

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/118#issuecomment-509624986))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0a72fcf5-777f-4162-8d9c-0f254feaede4, thread: pool-5-thread-3
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [23658142-594c-4c4b-bcfe-2984f59c00f1](https://www.0crat.com/footprint/CGC59KB9B/23658142-594c-4c4b-bcfe-2984f59c00f1), Type: "Transfer shares"

**Comment by 0crat** [comment]
> @0crat quality acceptable  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/118#issuecomment-509624986))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0a72fcf5-777f-4162-8d9c-0f254feaede4, thread: pool-5-thread-5
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [1e5411f5-0355-4085-a76c-7f4f2fbb98f5](https://www.0crat.com/footprint/CGC59KB9B/1e5411f5-0355-4085-a76c-7f4f2fbb98f5), Type: "Transfer shares"

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
