### ISSUE TITLE
Redesign invoice page

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#119]
Make a new design in Adobe XD for the invoice page

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c6675062-cc84-4507-ab95-22913e5b7093, thread: pool-19-thread-3
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.3' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.5](https://github.com/zerocracy/farm): CID: [0e2ee071-841b-4519-994f-273c23bb3686](https://www.0crat.com/footprint/CGC59KB9B/0e2ee071-841b-4519-994f-273c23bb3686), Type: "Job milestoned"

**Comment by amorenew** [comment]
@ammaratef45 check the new invoice if you have any notes

![iPhone X-XS – 5](https://user-images.githubusercontent.com/2842459/60767272-a3960f00-a0c6-11e9-9d6b-7b8c000158af.png)

**Comment by ammaratef45** [comment]
@amorenew Great, Thanks
please follow the discussion on the telegram group

**Comment by 0crat** [comment]
The job [#119](https://github.com/ammaratef45/zold-flutter-client/issues/119) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/40b1cae6-9280-4c12-ac4a-6fdd136b832d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#119` already assigned to @amorenew, can't assign to @amorenew

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@79d3ca93-2fb6-4bd9-98be-d4cf07e12042, thread: pool-24-thread-5
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [ac9eaeaf-65a7-4efc-b2ca-0fcafcec3294](https://www.0crat.com/footprint/CGC59KB9B/ac9eaeaf-65a7-4efc-b2ca-0fcafcec3294), Type: "Transfer shares"

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@amorenew The design is approved (I'll implement it), thanks

**Comment by 0crat** [comment]
Job was finished in 19 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @amorenew[/z](https://www.0crat.com/u/amorenew), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#119](https://github.com/ammaratef45/zold-flutter-client/issues/119) is now out of scope

**Comment by 0crat** [comment]
Job [#119](https://github.com/ammaratef45/zold-flutter-client/issues/119) is not in the agenda of @amorenew[/z](https://www.0crat.com/u/amorenew), can't inspect

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/ammaratef45/zold-flutter-client/issues/119#issuecomment-509142509))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@79d3ca93-2fb6-4bd9-98be-d4cf07e12042, thread: pool-24-thread-6
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [45e805ba-aa12-44f6-93ae-bdb4ceaebdfe](https://www.0crat.com/footprint/CGC59KB9B/45e805ba-aa12-44f6-93ae-bdb4ceaebdfe), Type: "Transfer shares"

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/ammaratef45/zold-flutter-client/issues/119#issuecomment-509142509))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@79d3ca93-2fb6-4bd9-98be-d4cf07e12042, thread: pool-24-thread-7
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [540a0c88-2491-49e5-837f-e54a01628f38](https://www.0crat.com/footprint/CGC59KB9B/540a0c88-2491-49e5-837f-e54a01628f38), Type: "Transfer shares"

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
