### ISSUE TITLE
Redesign pay page

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#120]
Make a new design in Adobe XD for the pay page

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c6675062-cc84-4507-ab95-22913e5b7093, thread: pool-19-thread-2
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.3' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.5](https://github.com/zerocracy/farm): CID: [41f48866-825e-4a0e-8016-aba7c2a7ed0c](https://www.0crat.com/footprint/CGC59KB9B/41f48866-825e-4a0e-8016-aba7c2a7ed0c), Type: "Job milestoned"

**Comment by 0crat** [comment]
The job [#120](https://github.com/ammaratef45/zold-flutter-client/issues/120) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/812d741a-84c6-4a9a-920f-4a482ebfc134); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@79d3ca93-2fb6-4bd9-98be-d4cf07e12042, thread: pool-24-thread-4
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [839cf3d6-2e02-4ca9-b451-f6d03a533542](https://www.0crat.com/footprint/CGC59KB9B/839cf3d6-2e02-4ca9-b451-f6d03a533542), Type: "Transfer shares"

**Comment by amorenew** [comment]
@ammaratef45 Payment design

![Design Guidelines@3x](https://user-images.githubusercontent.com/2842459/60860685-ae68b500-a228-11e9-8e08-f0162f753943.png)
![Payment@3x](https://user-images.githubusercontent.com/2842459/60860686-ae68b500-a228-11e9-945b-8438309f139c.png)

**Comment by ammaratef45** [comment]
@amorenew thanks

**Comment by 0crat** [comment]
Job was finished in 43 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#120](https://github.com/ammaratef45/zold-flutter-client/issues/120) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @amorenew[/z](https://www.0crat.com/u/amorenew), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#120](https://github.com/ammaratef45/zold-flutter-client/issues/120) is not in the agenda of @amorenew[/z](https://www.0crat.com/u/amorenew), can't inspect

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/ammaratef45/zold-flutter-client/issues/120#issuecomment-509537859))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@7ecdb09e-be36-42f7-a3b5-c47fb3817ccc, thread: pool-5-thread-5
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [28301649-fc08-40e2-8507-1e8d742dfc69](https://www.0crat.com/footprint/CGC59KB9B/28301649-fc08-40e2-8507-1e8d742dfc69), Type: "Transfer shares"

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/ammaratef45/zold-flutter-client/issues/120#issuecomment-509537859))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@7ecdb09e-be36-42f7-a3b5-c47fb3817ccc, thread: pool-5-thread-3
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [d4aa2a02-6579-4e01-860a-7e9c19c72667](https://www.0crat.com/footprint/CGC59KB9B/d4aa2a02-6579-4e01-860a-7e9c19c72667), Type: "Transfer shares"

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
