### ISSUE TITLE
[BUG] local_auth build fails for android

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#121]
When I try to build for Android, I get the following:

>/opt/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-0.3.1/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java:8: error: package android.support.v4.hardware.fingerprint does not exist
import android.support.v4.hardware.fingerprint.FingerprintManagerCompat;

**Comment by 0crat** [comment]
The job [#121](https://github.com/ammaratef45/zold-flutter-client/issues/121) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/3d5c3d23-bc7c-4144-93ca-30251ac2137b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f154a63e-7951-40f4-a819-ade93ae634d2, thread: pool-24-thread-6
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.2' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.5](https://github.com/zerocracy/farm): CID: [cb68ff3e-3684-4f92-a5d0-988d26c06600](https://www.0crat.com/footprint/CGC59KB9B/cb68ff3e-3684-4f92-a5d0-988d26c06600), Type: "Job milestoned"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f154a63e-7951-40f4-a819-ade93ae634d2, thread: pool-24-thread-4
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.5](https://github.com/zerocracy/farm): CID: [430297e1-95d5-431a-b9ab-85b27c92fcda](https://www.0crat.com/footprint/CGC59KB9B/430297e1-95d5-431a-b9ab-85b27c92fcda), Type: "Transfer shares"

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f154a63e-7951-40f4-a819-ade93ae634d2, thread: pool-24-thread-2
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.5](https://github.com/zerocracy/farm): CID: [ccef1039-9fdc-46c2-a4c3-aab01407c603](https://www.0crat.com/footprint/CGC59KB9B/ccef1039-9fdc-46c2-a4c3-aab01407c603), Type: "Transfer shares"

**Comment by 0crat** [comment]
The job [#121](https://github.com/ammaratef45/zold-flutter-client/issues/121) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
