### ISSUE TITLE
[BUG] App crashes in 64 bits phones

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#122]
In 64bit arc mobiles (like Huawei P20 Pro (HWCLT)), app crashes with the following stack trace

>java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1012)
  at java.lang.System.loadLibrary (System.java:1672)
  at io.flutter.view.FlutterMain.startInitialization (FlutterMain.java:164)
  at io.flutter.view.FlutterMain.startInitialization (FlutterMain.java:140)
  at io.flutter.app.FlutterApplication.onCreate (FlutterApplication.java:22)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1162)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6566)
  at android.app.ActivityThread.access$1900 (ActivityThread.java:267)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1963)
  at android.os.Handler.dispatchMessage (Handler.java:109)
  at android.os.Looper.loop (Looper.java:207)
  at android.app.ActivityThread.main (ActivityThread.java:7470)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:958)

Issue on flutter repo: flutter/flutter#23055

More about the issue in [this areticle](https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd)

**Comment by 0crat** [comment]
Job [#122](https://github.com/ammaratef45/zold-flutter-client/issues/122) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@172b6e24-c076-4e67-b31d-0a5185ba3ff6, thread: pool-5-thread-8
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.2' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.5](https://github.com/zerocracy/farm): CID: [f4334a45-cee7-4a9e-a436-e419f359f69b](https://www.0crat.com/footprint/CGC59KB9B/f4334a45-cee7-4a9e-a436-e419f359f69b), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#122` already assigned to @ammaratef45, can't assign to @ammaratef45

**Comment by 0crat** [comment]
The job [#122](https://github.com/ammaratef45/zold-flutter-client/issues/122) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/89a766f3-f1c6-409c-a91a-8eeb844b0618); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@172b6e24-c076-4e67-b31d-0a5185ba3ff6, thread: pool-5-thread-7
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.5](https://github.com/zerocracy/farm): CID: [50b7a60a-0249-470c-a0ea-fdd8917b065a](https://www.0crat.com/footprint/CGC59KB9B/50b7a60a-0249-470c-a0ea-fdd8917b065a), Type: "Transfer shares"

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@emilianodellacasa 
You can download the app [from here](https://mandrillapp.com/track/click/31095621/api.codemagic.io?p=eyJzIjoiWFU4WUJSOVB5SXd5VUpieVN6cjktaTRETWRRIiwidiI6MSwicCI6IntcInVcIjozMTA5NTYyMSxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2FwaS5jb2RlbWFnaWMuaW9cXFwvYXJ0aWZhY3RzXFxcL2M5ZTJmNTNiLTRmYTctNDE5Zi05NGY1LTk2OTljMTk0OTQ2NlxcXC81Mjc2Y2FhZC1iY2YzLTQ1NzgtOTBmNy01YTM5OTM2NmZlZjNcXFwvYXBwLXJlbGVhc2UuYXBrXCIsXCJpZFwiOlwiOWEzNTZiYWM0N2E3NDQ0YjhhYWJmYjg4YmJhYmRjOWVcIixcInVybF9pZHNcIjpbXCIxM2I4NDYzNGFmYzM2NGU5MTQ2MjIzNTcwMzFjZGMxNTY5ZGFkNDdjXCJdfSJ9) or wait for the google play update

Sorry for bothering you about it, I don't have a 64bit phone to test on it.

If the app opens normally, please confirm to me.

**Comment by emilianodellacasa** [comment]
@ammaratef45 Working perfectly, thanks a lot!

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@172b6e24-c076-4e67-b31d-0a5185ba3ff6, thread: pool-5-thread-2
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.65.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.47.5](https://github.com/zerocracy/farm): CID: [1eab3746-6eaf-4378-93fe-bf515575c6be](https://www.0crat.com/footprint/CGC59KB9B/1eab3746-6eaf-4378-93fe-bf515575c6be), Type: "Transfer shares"

**Comment by 0crat** [comment]
The job [#122](https://github.com/ammaratef45/zold-flutter-client/issues/122) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
