### ISSUE TITLE
Implement new invoice design

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#124]
Implement the design from #119 
Edits on the design:
1- remove dots from the hint text.
2- change text boxes to match the app theme

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@79d3ca93-2fb6-4bd9-98be-d4cf07e12042, thread: pool-24-thread-3
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.3' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.48](https://github.com/zerocracy/farm): CID: [ea60a91c-1b62-4f60-b09a-e952bc97101b](https://www.0crat.com/footprint/CGC59KB9B/ea60a91c-1b62-4f60-b09a-e952bc97101b), Type: "Job milestoned"

**Comment by 0crat** [comment]
The job [#124](https://github.com/ammaratef45/zold-flutter-client/issues/124) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/b3350668-c192-4287-8e02-3a9d0744363f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@79d3ca93-2fb6-4bd9-98be-d4cf07e12042, thread: pool-24-thread-1
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [b28c7ade-6b54-45ec-bbed-25ac6fb486ed](https://www.0crat.com/footprint/CGC59KB9B/b28c7ade-6b54-45ec-bbed-25ac6fb486ed), Type: "Transfer shares"

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#124](https://github.com/ammaratef45/zold-flutter-client/issues/124) is now out of scope

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@79d3ca93-2fb6-4bd9-98be-d4cf07e12042, thread: pool-24-thread-6
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [413153af-f47d-4eb1-a4d2-e4549f4be7ba](https://www.0crat.com/footprint/CGC59KB9B/413153af-f47d-4eb1-a4d2-e4549f4be7ba), Type: "Transfer shares"

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
