### ISSUE TITLE
Implement new homepage design

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#125]
Implement the design from #118 once submitted by @amorenew

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@79d3ca93-2fb6-4bd9-98be-d4cf07e12042, thread: pool-24-thread-1
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.3' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.48](https://github.com/zerocracy/farm): CID: [a46c94d8-6fdd-4c36-acc5-000759d997a1](https://www.0crat.com/footprint/CGC59KB9B/a46c94d8-6fdd-4c36-acc5-000759d997a1), Type: "Job milestoned"

**Comment by 0crat** [comment]
The job [#125](https://github.com/ammaratef45/zold-flutter-client/issues/125) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/5b2f932d-c67f-462e-b49d-f2da87fc0221); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#125` already assigned to @ammaratef45, can't assign to @ammaratef45

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@79d3ca93-2fb6-4bd9-98be-d4cf07e12042, thread: pool-24-thread-5
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [8c30058f-0984-478c-983f-8e16c3cc80e8](https://www.0crat.com/footprint/CGC59KB9B/8c30058f-0984-478c-983f-8e16c3cc80e8), Type: "Transfer shares"

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by amorenew** [comment]
@ammaratef45 the redesign and guideline
![Design Guidelines@3x](https://user-images.githubusercontent.com/2842459/60860566-2da9b900-a228-11e9-99fa-4179f6d7c229.png)

![Dashboard@3x](https://user-images.githubusercontent.com/2842459/60860550-166acb80-a228-11e9-90f2-16f7dee96ebb.png)

**Comment by 0pdd** [comment]
@ammaratef45 the puzzle [#128](https://github.com/ammaratef45/zold-flutter-client/issues/128) is still not solved.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b5957bde-43f3-4887-806b-3b28b4e95496, thread: pool-5-thread-4
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48](https://github.com/zerocracy/farm): CID: [b46c8b9d-893c-430c-b3e4-73fb5c346363](https://www.0crat.com/footprint/CGC59KB9B/b46c8b9d-893c-430c-b3e4-73fb5c346363), Type: "Transfer shares"

**Comment by 0crat** [comment]
The job [#125](https://github.com/ammaratef45/zold-flutter-client/issues/125) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
