### ISSUE TITLE
Implement the settings page

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#126]
Implement the design made by @amorenew 
Consider changing the icons

![photo_٢٠١٩-٠٧-٠٩_٠٦-٤٢-٠٣](https://user-images.githubusercontent.com/13663221/61029913-78f4d080-a3bc-11e9-8a8e-140a6e47a5a3.jpg)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dcc14a3c-92cf-441b-87df-6f5794ddb569, thread: pool-3-thread-7
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.3' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.48](https://github.com/zerocracy/farm): CID: [36b63d27-7856-46bd-a90f-bf6b3d8c33cd](https://www.0crat.com/footprint/CGC59KB9B/36b63d27-7856-46bd-a90f-bf6b3d8c33cd), Type: "Job milestoned"

**Comment by amreniouinnovent** [comment]
@ammaratef45 I recommend sing Listview(), IconButton() and Divider() same like what we do in the drawer

```
 SafeArea(
          child: ListView(
            // Important: Remove any padding from the ListView.
            padding: EdgeInsets.zero,
            children: <Widget>[ListTile(
                title: Text(
                  'Route',
                  style: TextStyle(
                      color: AppColors.darkBlack,
                      fontFamily: AppFonts.localeFont(context),
                      fontSize: 16),
                ),
                onTap: () {
                  // Update the state of the app.
                  // ...
                },
              ),
              const Divider(
                height: 0,
              )
```

**Comment by ammaratef45** [comment]
@amorenew want to implement it? I will review the PR in less than 24 hours if you did

**Comment by amreniouinnovent** [comment]
@ammaratef45 it is easy but I don't have the internet at home this month but next month I will be able to participate in the project again

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#126` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
