### ISSUE TITLE
Implement new pay design

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#127]
Implement the design from #120 made by @amorenew

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dcc14a3c-92cf-441b-87df-6f5794ddb569, thread: pool-3-thread-2
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.3' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.48](https://github.com/zerocracy/farm): CID: [82155886-66d6-4d39-bbde-d6a37efb7b15](https://www.0crat.com/footprint/CGC59KB9B/82155886-66d6-4d39-bbde-d6a37efb7b15), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#127` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
