### ISSUE TITLE
Add Flutter web support for testing purpose

### ISSUE THREAD

**Issue by amorenew** [ammaratef45/zold-flutter-client#129]
**Is your feature request related to a problem? Please describe.**
The iPhone design is not perfect
 
**Describe the solution you'd like**
It would be more easy to run the project in Chrome and test the responsive design there.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#129](https://github.com/ammaratef45/zold-flutter-client/issues/129) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cfefddef-8b0d-4288-b08a-bc51f02ab516, thread: pool-15-thread-5
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.66.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48.2](https://github.com/zerocracy/farm): CID: [9e26dd2e-211d-4a2e-8ef6-01628bb00159](https://www.0crat.com/footprint/CGC59KB9B/9e26dd2e-211d-4a2e-8ef6-01628bb00159), Type: "Transfer shares"

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
The job [#129](https://github.com/ammaratef45/zold-flutter-client/issues/129) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/55e8d0b0-d7dd-490f-8950-1a3dfbd38e9e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@amorenew 
in the https://flutter.dev FAQ
Flutter web is currently in technical preview. We are developing Flutter for web in a fork of the Flutter repo. This enables fast iterations while keeping the core Flutter repo stable. You can repackage existing Flutter code to work on the web preview, but there are some caveats while we’re still in preview.
[Reference](https://flutter.dev/docs/resources/faq#does-flutter-run-on-the-web)

I guess we may need to wait for a stable release to avoid making unnecessary changes.
WDYT?

**Comment by amreniouinnovent** [comment]
@ammaratef45 we are not supporting web we just targeting web for UI testing

**Comment by ammaratef45** [comment]
@amorenew still you need to add changes for the build to be done

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@0crat wait for flutter web first stable release

**Comment by 0crat** [comment]
> @0crat wait for flutter web first stable release ([here](https://github.com/ammaratef45/zold-flutter-client/issues/129#issuecomment-513463643))

@ammaratef45 The impediment for [#129](https://github.com/ammaratef45/zold-flutter-client/issues/129) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/ammaratef45/zold-flutter-client/issues/129#issuecomment-607907812))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#129](https://github.com/ammaratef45/zold-flutter-client/issues/129), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#129](https://github.com/ammaratef45/zold-flutter-client/issues/129); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#129](https://github.com/ammaratef45/zold-flutter-client/issues/129); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by amreniouinnovent** [comment]
Flutter web is not mature yet
It requires 6 months to be ok
I will close this issue until the Flutter web became more mature.
@ammaratef45 Could you close it I don't have the permission

**Comment by ammaratef45** [comment]
@amreniouinnovent thanks

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#129` is not assigned, can't get performer
