### ISSUE TITLE
Add a privacy policy

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#13]
Later google play may unpublish the app if we didn't add a privacy policy
We need to add one, Probably as an markdown file `policy.md`

**Comment by amrboxit4me** [comment]
I never faced this issue before for Android Playstore
I think for low installs apps policy is not important
But for sure Apple Appstore will make a problem

**Comment by ammaratef45** [comment]
@amrboxit4me It's not an urgent issue, but later it would be a problem

**Comment by 0crat** [comment]
Job [#13](https://github.com/ammaratef45/zold-flutter-client/issues/13) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#13](https://github.com/ammaratef45/zold-flutter-client/issues/13); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#13](https://github.com/ammaratef45/zold-flutter-client/issues/13); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by ammaratef45** [comment]
@amrboxit4me last time I was trying to deploy I got this
>Google Api Error: apkPermissionsRequirePrivacyPolicy: The apk has permissions that require a privacy policy set for the app, e.g: android.permission.CAMERA.

Look? 😆

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#13](https://github.com/ammaratef45/zold-flutter-client/issues/13); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#13](https://github.com/ammaratef45/zold-flutter-client/issues/13) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/4c4f5d1c-a6fd-4fbd-b8d0-7a0eac03963a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Job was finished in 6 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#13](https://github.com/ammaratef45/zold-flutter-client/issues/13) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
