### ISSUE TITLE
Iphone UI enhancement 

### ISSUE THREAD

**Issue by amreniouinnovent** [ammaratef45/zold-flutter-client#130]
The application UI is not fit to iPhone devices
There should be a test for iPhone device and a better responsive support

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@amreniouinnovent[/z](https://www.0crat.com/u/amreniouinnovent) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#130](https://github.com/ammaratef45/zold-flutter-client/issues/130) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/f3431850-3713-41b8-b16a-9575c6ff70e8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Thanks for your contribution, @amreniouinnovent[/z](https://www.0crat.com/u/amreniouinnovent)! If you would be a member of [the project](https://www.0crat.com/p/CGC59KB9B), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@amorenew We have a problem when the phone font is large on the device

I have some solutions in mind and want to know what you may like as a user
1- showing only a part of the id when there is no enough space
2- breaking the info in two lines

WDYT?

**Comment by amorenew** [comment]
@ammaratef45 I think it requires R&D then we could reduce the font size by delta
or maybe we would need a plugin
https://stackoverflow.com/questions/16544931/read-font-size-from-settings
```
return MaterialApp(
  home: HomeScreen(),
  builder: (context, navigator) {
    var lang = Localizations.localeOf(context).languageCode;

    return Theme(
      data: ThemeData(
        textTheme: Theme.of(context).textTheme.apply(
          fontFamily: lang == 'ar'? 
            'FrutigerLTArabic' : 'ProximaNova',
          fontSizeDelta: lang == 'ar'? -5.0 : 0.0
        ),
      ),
      child: navigator,
    );
  },
);

```

**Comment by amorenew** [comment]
@ammaratef45 alternative solution using auto resize text widget
https://pub.dev/packages/auto_size_text

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@amorenew Thanks for the suggestions
most probably flexible solved the issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@2d884006-fb42-41c7-95ee-f335128adb64, thread: pool-5-thread-7
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.66.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.48.8](https://github.com/zerocracy/farm): CID: [97b69fd1-7c1f-4cf7-8597-2042bf15153d](https://www.0crat.com/footprint/CGC59KB9B/97b69fd1-7c1f-4cf7-8597-2042bf15153d), Type: "Transfer shares"

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#130](https://github.com/ammaratef45/zold-flutter-client/issues/130) is now out of scope
