### ISSUE TITLE
version increment

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#15]
needs to configure Fastlane for automatic version increment to avoid deployment errors

**Comment by 0crat** [comment]
Job [#15](https://github.com/ammaratef45/zold-flutter-client/issues/15) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#15](https://github.com/ammaratef45/zold-flutter-client/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#15](https://github.com/ammaratef45/zold-flutter-client/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#15](https://github.com/ammaratef45/zold-flutter-client/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#15](https://github.com/ammaratef45/zold-flutter-client/issues/15); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by ammaratef45** [comment]
Will not implement this as we are deploying with codemagic instead of Fastlane currently

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#15` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#15](https://github.com/ammaratef45/zold-flutter-client/issues/15) is now out of scope
