### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#16]
Readme file is not good at all now,
update it to show more details.

**Comment by 0crat** [comment]
Job [#16](https://github.com/ammaratef45/zold-flutter-client/issues/16) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#16](https://github.com/ammaratef45/zold-flutter-client/issues/16); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#16` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#16](https://github.com/ammaratef45/zold-flutter-client/issues/16) is now out of scope
