### ISSUE TITLE
Show jobs status

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#17]
wts returns a job id which log can be retrieved using /output endpoint
Use it and add a button for the user to see the log.

**Comment by yegor256** [comment]
I think that the entire screen should dim when I start ANY job, and should show me the progress. Then, when it's complete, it shows me the result, like "OK" or "sorry, failure, here is a full log" and then I have access to the screen again. I would do it this way.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#17` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
