### ISSUE TITLE
Add QR payment

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#18]
Let the user be able to make a payment by scanning a QR or generating a QR to receive payments.

**Comment by 0crat** [comment]
Job [#18](https://github.com/ammaratef45/zold-flutter-client/issues/18) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#18` already assigned to @ammaratef45, can't assign to @ammaratef45

**Comment by 0crat** [comment]
The job [#18](https://github.com/ammaratef45/zold-flutter-client/issues/18) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/42d96933-fc5d-46b5-a3ea-b2c774a35c42); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 2 puzzles [#24](https://github.com/ammaratef45/zold-flutter-client/issues/24), [#25](https://github.com/ammaratef45/zold-flutter-client/issues/25) are still not solved.

**Comment by ammaratef45** [comment]
@rultor deploy

**Comment by ammaratef45** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/ammaratef45/zold-flutter-client/issues/18#issuecomment-473619189))

@ammaratef45 This is what I know about this job in [CGC59KB9B](https://www.0crat.com/p/CGC59KB9B), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#18](https://github.com/ammaratef45/zold-flutter-client/issues/18) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `DEV`
  * The job is assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @ammaratef45[/z](https://www.0crat.com/u/ammaratef45): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CGC59KB9B?q=%7Bjob%3A%27gh%3Aammaratef45%2Fzold-flutter-client%2318%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ammaratef45** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/ammaratef45/zold-flutter-client/issues/18#issuecomment-473619859))

@ammaratef45 The job [#18](https://github.com/ammaratef45/zold-flutter-client/issues/18) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 the puzzle [#24](https://github.com/ammaratef45/zold-flutter-client/issues/24) is still not solved; solved: [#25](https://github.com/ammaratef45/zold-flutter-client/issues/25).

**Comment by 0pdd** [comment]
@ammaratef45 all 2 puzzles are solved here: [#24](https://github.com/ammaratef45/zold-flutter-client/issues/24), [#25](https://github.com/ammaratef45/zold-flutter-client/issues/25).
