### ISSUE TITLE
add ability to scan details from QR.

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/zold-flutter-client#24]
The puzzle `18-7ef2e369` from #18 has to be resolved: 

https://github.com/ammaratef45/zold-flutter-client/blob/a934089ac0b958110115776e045e78e76fdad42b/zold_wallet/lib/pay_page/pay_page_viewmodel.dart#L29-L29

The puzzle was created by @rultor on 14-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#24](https://github.com/ammaratef45/zold-flutter-client/issues/24) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `18-7ef2e369` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#24` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#24](https://github.com/ammaratef45/zold-flutter-client/issues/24) is now out of scope
