### ISSUE TITLE
add share methods to native code.

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/zold-flutter-client#25]
The puzzle `18-5d314318` from #18 has to be resolved: 

https://github.com/ammaratef45/zold-flutter-client/blob/a934089ac0b958110115776e045e78e76fdad42b/zold_wallet/lib/create_page/create_page_viewmodel.dart#L45-L45

The puzzle was created by @rultor on 14-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#25](https://github.com/ammaratef45/zold-flutter-client/issues/25) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `18-5d314318` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#25` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#25](https://github.com/ammaratef45/zold-flutter-client/issues/25) is now out of scope
