### ISSUE TITLE
just a spinner is not enough

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#26]
When you are doing "pull" or some other operation, you are showing a simple spinner. Since the operation takes longer than a few seconds, such a simple UI is not enough. Instead, I would suggest to show a spinner and a number, which will show the amount of bytes in the job "output". This number will grow when the job is working. We can add a simple end-point in WTS, like `/output/size` to make it faster.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#26](https://github.com/ammaratef45/zold-flutter-client/issues/26) is now in scope, role is `DEV`

**Comment by ammaratef45** [comment]
@yegor256 Can you add a number that represents the average size of output? that may be good too.

**Comment by yegor256** [comment]
@ammaratef45 make a ticket in WTS

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ammaratef45** [comment]
@yegor256 I added zold-io/wts.zold.io#190

**Comment by 0crat** [comment]
The job [#26](https://github.com/ammaratef45/zold-flutter-client/issues/26) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/c26c3b00-ccef-4cf8-9a86-d6d33d776230); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#39](https://github.com/ammaratef45/zold-flutter-client/issues/39) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 43 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#26](https://github.com/ammaratef45/zold-flutter-client/issues/26) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#39](https://github.com/ammaratef45/zold-flutter-client/issues/39) is solved here.
