### ISSUE TITLE
empty wallet must say "wallet is empty"

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#27]
At the moment my mobile wallet is empty and I don't see any transactions. I should see something like "Your wallet is empty, there are no transactions as of yet".

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ammaratef45** [comment]
@yegor256, for now, we are not displaying the transactions, we should take care of this when adding it.

**Comment by 0crat** [comment]
Job [#27](https://github.com/ammaratef45/zold-flutter-client/issues/27) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#27](https://github.com/ammaratef45/zold-flutter-client/issues/27) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/98f07775-573b-4de1-999c-703b004d76c0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#41](https://github.com/ammaratef45/zold-flutter-client/issues/41), [#42](https://github.com/ammaratef45/zold-flutter-client/issues/42), [#43](https://github.com/ammaratef45/zold-flutter-client/issues/43) are still not solved.

**Comment by 0crat** [comment]
Job was finished in 43 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#27](https://github.com/ammaratef45/zold-flutter-client/issues/27) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#42](https://github.com/ammaratef45/zold-flutter-client/issues/42) is still not solved; solved: [#41](https://github.com/ammaratef45/zold-flutter-client/issues/41), [#43](https://github.com/ammaratef45/zold-flutter-client/issues/43).

**Comment by 0pdd** [comment]
@yegor256 all 3 puzzles are solved here: [#41](https://github.com/ammaratef45/zold-flutter-client/issues/41), [#42](https://github.com/ammaratef45/zold-flutter-client/issues/42), [#43](https://github.com/ammaratef45/zold-flutter-client/issues/43).
