### ISSUE TITLE
"Copy wallet ID" is missing

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#29]
At the moment on the front/home page, I don't see a button to copy the wallet ID in the clipboard. Would be convenient if I would be able to click a small icon and copy the ID.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#29](https://github.com/ammaratef45/zold-flutter-client/issues/29) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#29` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#29](https://github.com/ammaratef45/zold-flutter-client/issues/29) is now out of scope
