### ISSUE TITLE
Move redundant dialogs

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#31]
Error dialogs and waiting dialogs are redundant in more than one page, should be moved to a reusable module

**Comment by 0crat** [comment]
Job [#31](https://github.com/ammaratef45/zold-flutter-client/issues/31) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#31](https://github.com/ammaratef45/zold-flutter-client/issues/31); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0pdd** [comment]
@ammaratef45 the puzzle [#34](https://github.com/ammaratef45/zold-flutter-client/issues/34) is still not solved.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#31` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#31](https://github.com/ammaratef45/zold-flutter-client/issues/31) is now out of scope

**Comment by 0pdd** [comment]
@ammaratef45 the puzzle [#44](https://github.com/ammaratef45/zold-flutter-client/issues/44) is still not solved; solved: [#34](https://github.com/ammaratef45/zold-flutter-client/issues/34).

**Comment by 0pdd** [comment]
@ammaratef45 all 2 puzzles are solved here: [#34](https://github.com/ammaratef45/zold-flutter-client/issues/34), [#44](https://github.com/ammaratef45/zold-flutter-client/issues/44).
