### ISSUE TITLE
remove this function and make sure not to lose any functionality

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/zold-flutter-client#34]
The puzzle `31-0d7dcb0d` from #31 has to be resolved: 

https://github.com/ammaratef45/zold-flutter-client/blob/1d27fd8dec8cc160ca7dfa4233083814e81d63a9/zold_wallet/lib/login_page/login_page_view_model.dart#L36-L36

The puzzle was created by Ammar Atef on 18-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#34](https://github.com/ammaratef45/zold-flutter-client/issues/34) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#34](https://github.com/ammaratef45/zold-flutter-client/issues/34) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/0223a321-b9b4-4895-89ee-cd950a9e3000); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `31-0d7dcb0d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#44](https://github.com/ammaratef45/zold-flutter-client/issues/44) is still not solved.

**Comment by 0crat** [comment]
The job [#34](https://github.com/ammaratef45/zold-flutter-client/issues/34) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#44](https://github.com/ammaratef45/zold-flutter-client/issues/44) is solved here.
