### ISSUE TITLE
UI Suggestion

### ISSUE THREAD

**Issue by amorenew** [ammaratef45/zold-flutter-client#38]
I have a UI suggestion for the app as you can see in the image below.

![crypto_wallet_app](https://user-images.githubusercontent.com/2842459/54776377-6e55d600-4c29-11e9-9b9c-b9287ad78b7b.jpg)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ammaratef45** [comment]
@amorenew the right image looks good as structure
@yegor256 what do you think?

**Comment by 0crat** [comment]
Job [#38](https://github.com/ammaratef45/zold-flutter-client/issues/38) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
The job [#38](https://github.com/ammaratef45/zold-flutter-client/issues/38) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/f9bf8bf9-6c6d-4316-8a06-2e4f4a063c19); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 40 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#38](https://github.com/ammaratef45/zold-flutter-client/issues/38) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
