### ISSUE TITLE
get job id not a log from the callback. make the waiting loop here and get job file to show.

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/zold-flutter-client#39]
The puzzle `26-5375c740` from #26 has to be resolved: 

https://github.com/ammaratef45/zold-flutter-client/blob/f33dba903832ef3eea5309d8d1833c7caee68121/zold_wallet/lib/dialogs.dart#L22-L23

The puzzle was created by Ammar Atef on 23-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#39](https://github.com/ammaratef45/zold-flutter-client/issues/39) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#39](https://github.com/ammaratef45/zold-flutter-client/issues/39) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/97aa7dc8-662d-4f7d-acc0-c7cd15dccbb6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `26-5375c740` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 33 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#39](https://github.com/ammaratef45/zold-flutter-client/issues/39) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
