### ISSUE TITLE
sort desc, add more info and show better design

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/zold-flutter-client#42]
The puzzle `27-82704f59` from #27 has to be resolved: 

https://github.com/ammaratef45/zold-flutter-client/blob/0e88a41ea71fb23cfef893a48876eec75caef41c/zold_wallet/lib/home_page/home_page_view.dart#L62-L62

The puzzle was created by Ammar Atef on 23-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#42](https://github.com/ammaratef45/zold-flutter-client/issues/42) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#42](https://github.com/ammaratef45/zold-flutter-client/issues/42) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/b45d7d9d-37aa-4b75-80c1-0b67dfd7e56f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `27-82704f59` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 33 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#42](https://github.com/ammaratef45/zold-flutter-client/issues/42) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
