### ISSUE TITLE
fingerprint authentication on iPhone

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#54]
Would be great to remember the keygap inside the app and let me send the payment with just a fingerprint scan. The iPhone has this feature. Or a facescan in the newest iPhone. Now I have to enter my keygap every time and it's pretty time consuming and not convenient at all.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#54](https://github.com/ammaratef45/zold-flutter-client/issues/54) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#54](https://github.com/ammaratef45/zold-flutter-client/issues/54) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/43531bd3-88c1-445a-b303-baf5f393a7b6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#68](https://github.com/ammaratef45/zold-flutter-client/issues/68) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 9 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#54](https://github.com/ammaratef45/zold-flutter-client/issues/54) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#68](https://github.com/ammaratef45/zold-flutter-client/issues/68) is solved here.
