### ISSUE TITLE
save and retreaive keygap from shared prefs. make keygap password shown. allow user to login with...

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/zold-flutter-client#68]
The puzzle `54-72d7e8a7` from #54 has to be resolved: 

https://github.com/ammaratef45/zold-flutter-client/blob/2009c067926ff12c732c512b53502c3e53d96071/zold_wallet/lib/pay_page/pay_page_viewmodel.dart#L37-L40

The puzzle was created by Ammar Atef on 31-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#68](https://github.com/ammaratef45/zold-flutter-client/issues/68) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#68](https://github.com/ammaratef45/zold-flutter-client/issues/68) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/3f42ef7a-323c-4af1-90c8-a794bfdeb2ff); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `54-72d7e8a7` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 8 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#68](https://github.com/ammaratef45/zold-flutter-client/issues/68) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
