### ISSUE TITLE
installation steps

### ISSUE THREAD

**Issue by amorenew** [ammaratef45/zold-flutter-client#7]
How could I install the app on windows?
I got an error
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because zold_wallet requires SDK version >=2.1.0 <3.0.0, version solving failed.

it got solved by the following commans
```
flutter channel dev
flutter upgrade
```

**Comment by ammaratef45** [comment]
@amorenew Thanks
