### ISSUE TITLE
multiple clicks at icons

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#70]
Try to click multiple times at those "copy wallet ID" icon, fast. You will see what happens.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ammaratef45** [comment]
@yegor256 It will let the snack bar (bottom message bar) appear and disappear like forever, right?

**Comment by 0crat** [comment]
Job [#70](https://github.com/ammaratef45/zold-flutter-client/issues/70) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#70](https://github.com/ammaratef45/zold-flutter-client/issues/70) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/63244383-2f7c-4c60-af37-9467ba07ad13); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat wait
I've posted [a question on stackoverflow](https://stackoverflow.com/questions/55547443/flutter-how-to-disable-ontap-for-a-while-in-gesture-detector) to avoid changing the structure for solving this.
I will be working on it again after a week if no solution was received.

**Comment by 0crat** [comment]
> @0crat wait I've posted [a question on stackoverflow](https://stackoverflow.com/questions/555474... ([here](https://github.com/ammaratef45/zold-flutter-client/issues/70#issuecomment-480487762))

@ammaratef45 The impediment for [#70](https://github.com/ammaratef45/zold-flutter-client/issues/70) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#70](https://github.com/ammaratef45/zold-flutter-client/issues/70) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
