### ISSUE TITLE
login page must be broken down into three

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#80]
At the moment there is one big login page. It's not convenient. Instead, there should be three.

1. Login. You ask for a phone number and that's it. There is one field for the number (remove the drop down with the list of countries) and a button "Send me the code". Also, at this page should be a link/text saying "Use auth code instead". Also, put the "+" sign right before the input field. Also, when I enter the phone number, I should see my country name right beneath it.

2. Code. Show this page when the user clicked "send me the code" and you sent the code. At this page the user should enter the code into the field and click "Enter". Also, at this page put a link/text "Didn't receive the code?" When the user clicks that link, he gets back to the Login page.

3. Auth. At this page the user should enter the auth token and click "Enter". Also, there should be a text/link "Use mobile phone instead" which leads to the Login page.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#80](https://github.com/ammaratef45/zold-flutter-client/issues/80) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/f0419fba-7c73-457b-ad30-1653e40f220b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job was finished in 41 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#80](https://github.com/ammaratef45/zold-flutter-client/issues/80) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
