### ISSUE TITLE
logo is not correct

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#81]
Use this one.
![logo](https://user-images.githubusercontent.com/526301/55456144-f73c1c80-55ee-11e9-9c5c-68566c054a66.png)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#81](https://github.com/ammaratef45/zold-flutter-client/issues/81) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/45ea5fa0-8119-4339-8edd-37160c220c2c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#81` already assigned to @ammaratef45, can't assign to @ammaratef45

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ammaratef45** [comment]
@yegor256 the logo is used in many places
 1-  the logo in the app store.
 2- the launcher icon.
 3- the image in the README file.
 4- the image in the app bar.
 5- in the login page as in the new design (not deployed yet)
you want me to replace all of them?
Because the white background may look better in some places.

**Comment by ammaratef45** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/ammaratef45/zold-flutter-client/issues/81#issuecomment-480553367))

@ammaratef45 GitHub issue is still open, won't close

**Comment by ammaratef45** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/ammaratef45/zold-flutter-client/issues/81#issuecomment-480553493))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#81](https://github.com/ammaratef45/zold-flutter-client/issues/81), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@0crat out

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#81](https://github.com/ammaratef45/zold-flutter-client/issues/81); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/ammaratef45/zold-flutter-client/issues/81#issuecomment-480553648))

@ammaratef45 Job `gh:ammaratef45/zold-flutter-client#81` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/ammaratef45/zold-flutter-client/issues/81#issuecomment-480553648))

@ammaratef45 The job [#81](https://github.com/ammaratef45/zold-flutter-client/issues/81) is now out of scope

**Comment by yegor256** [comment]
@ammaratef45 can you please fix this?

**Comment by ammaratef45** [comment]
> @yegor256 the logo is used in many places
> 1- the logo in the app store.
> 2- the launcher icon.
> 3- the image in the README file.
> 4- the image in the app bar.
> 5- in the login page as in the new design (not deployed yet)
> you want me to replace all of them?
> Because the white background may look better in some places.

@yegor256 can you answer this please?

**Comment by yegor256** [comment]
@ammaratef45 it's better to use transparent images ALWAYS

**Comment by 0crat** [comment]
The job [#81](https://github.com/ammaratef45/zold-flutter-client/issues/81) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/2f96b988-208d-467e-a4c5-b0ae25668c72); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#81` already assigned to @ammaratef45, can't assign to @ammaratef45

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by amorenew** [comment]
@ammaratef45  I saw the logo it has a black background and it looks different than the website logo.
Is this the required result?

**Comment by ammaratef45** [comment]
@amorenew I doubt if it is the required result too.
/cc @yegor256

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@ammaratef45 it's OK now

**Comment by 0crat** [comment]
The job [#81](https://github.com/ammaratef45/zold-flutter-client/issues/81) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
