### ISSUE TITLE
all input fields must be the same as in the login page

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#90]
Let's make sure all input fields are the same controls like the one you use in the Login page.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#90](https://github.com/ammaratef45/zold-flutter-client/issues/90) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job [#90](https://github.com/ammaratef45/zold-flutter-client/issues/90) is already in scope

**Comment by 0crat** [comment]
The job [#90](https://github.com/ammaratef45/zold-flutter-client/issues/90) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/3c5b5208-14fa-425c-9727-9616da497571); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#90](https://github.com/ammaratef45/zold-flutter-client/issues/90) is now out of scope
