### ISSUE TITLE
Can't see the input field when I enter my mobile phone number

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#91]
See the screenshot:

![IMG_4917](https://user-images.githubusercontent.com/526301/55876210-bcfaee00-5b9f-11e9-9421-7be7b13560c8.PNG)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#91](https://github.com/ammaratef45/zold-flutter-client/issues/91) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#91](https://github.com/ammaratef45/zold-flutter-client/issues/91) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/1bf414c4-a074-42c1-94d7-c6fb70658af6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job [#91](https://github.com/ammaratef45/zold-flutter-client/issues/91) is already in scope

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#91](https://github.com/ammaratef45/zold-flutter-client/issues/91) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
