### ISSUE TITLE
UI tweaks

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#93]
Would be great if you can make a few UI tweaks.

1. Remove the header at all. Move the "logout" button to the bottom bar, far right position.

2. Increase the size of the font on the screen, by 40%.

3. Use the "monospaced" font

4. Make green and red ONLY the amounts, not the entire transaction block.

5. Make sure all texts have the same left/right margins.

6. Align everything ALWAYS left on ALL screens (including login)

7. Change `Balance: 3.98ZLD - 8.97USD` to `Balance: 3.98 ZLD ($8.97)`

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#93](https://github.com/ammaratef45/zold-flutter-client/issues/93) is now in scope, role is `DEV`

**Comment by amorenew** [comment]
@ammaratef45 I am now a beginner in FLutter and I can start a simple task like refactoring or simple UI fixes, etc
Could you make this issue as a separated task and assign me 1 task only as a beginning?
Thanks

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ammaratef45** [comment]
@yegor256 
>Align everything ALWAYS left on ALL screens (including login)

Including logo?

**Comment by ammaratef45** [comment]
@yegor256 please have a look.

**Comment by yegor256** [comment]
@ammaratef45 looks much better! I will create new tickets now.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#93` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#93](https://github.com/ammaratef45/zold-flutter-client/issues/93) is now out of scope
