### ISSUE TITLE
Font issues

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/zold-flutter-client#94]
A puzzle for #93 
We should use a custom text widget that has the default font size and family in the style and reuses it everywhere.

The task is to create a widget for the custom text and let it have a default font family and size then replace all `Text` widgets with it

**Comment by 0crat** [comment]
Job [#94](https://github.com/ammaratef45/zold-flutter-client/issues/94) is now in scope, role is `DEV`

**Comment by ammaratef45** [comment]
@amorenew what do you think about this? can you accomplish it?

**Comment by amorenew** [comment]
@ammaratef45 Yes I can, assign it to my account.
what is your expectation for the delivery date?

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@0crat assign @amorenew

**Comment by 0crat** [comment]
> @0crat assign @amorenew  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/94#issuecomment-492973353))

@ammaratef45 The job [#94](https://github.com/ammaratef45/zold-flutter-client/issues/94) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/8a6a5e64-21e1-4fd0-a3ca-e17aa356d582); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @amorenew[/z](https://www.0crat.com/u/amorenew) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
> @ammaratef45 Yes I can, assign it to my account.
> what is your expectation for the delivery date?

Sooner is better, you manage your schedule
Let me know if there are any barriers, I will facilitate whatever you want.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by amorenew** [comment]
@ammaratef45 Once the build #95  issue is fixed I can start this task.

**Comment by ammaratef45** [comment]
@amorenew FYI, you can ask zerocrat to hold the issue
for example say:
`@0crat wait for resolution of #95 `

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/ammaratef45/zold-flutter-client/issues/94#issuecomment-493367405); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by amorenew** [comment]
@ammaratef45 I made a widget but after R&D I found a better solution by using the theme I can make a default text style with font family and font size for Text widget only
check this >> https://api.flutter.dev/flutter/material/TextTheme-class.html
body1 is for Text widgets
```
theme: ThemeData(
        textTheme: TextTheme(body1: TextStyle(backgroundColor: Colors.red))
      )
```
So should I use Widget or define the default values in TextTheme?
![Screenshot_1558146880](https://user-images.githubusercontent.com/2842459/57963593-7464ec00-7926-11e9-95b6-b40b577efb75.png)

**Comment by ammaratef45** [comment]
@amorenew I prefer the solution you've found, let's go with it 😄

**Comment by amorenew** [comment]
@0crat wait for resolution of #97

**Comment by 0crat** [comment]
> @0crat wait for resolution of #97  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/94#issuecomment-493685584))

@amorenew The impediment for [#94](https://github.com/ammaratef45/zold-flutter-client/issues/94) was registered successfully by @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by ammaratef45** [comment]
@amorenew please don't wait for #97, It will not stop your work from being merged (tests will fail locally only)

**Comment by amorenew** [comment]
@0crat continue

**Comment by 0crat** [comment]
> @0crat continue  ([here](https://github.com/ammaratef45/zold-flutter-client/issues/94#issuecomment-493712156))

@amorenew @amorenew[/z](https://www.0crat.com/u/amorenew) continued working on job [#94](https://github.com/ammaratef45/zold-flutter-client/issues/94)

**Comment by ammaratef45** [comment]
@amorenew Good work.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @amorenew[/z](https://www.0crat.com/u/amorenew), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#94](https://github.com/ammaratef45/zold-flutter-client/issues/94) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
