### ISSUE TITLE
Error building the project

### ISSUE THREAD

**Issue by amorenew** [ammaratef45/zold-flutter-client#95]
**Describe the bug**
1-I couldn't run the project as a Flutter app in Visual Studio Code because you didn't commit the '.vscode' folder which is required for VS Code to recognize it as a Flutter app.
2-I got an error while running the project for android in the following line
```
Error: > path may not be null or empty string. path='null'
Build file 'zold_wallet\android\app\build.gradle' line: 47
storeFile file(keystoreProperties['storeFile'])

```
3-PDD documentation and docker is not clear.
do I need to install anything more or it is not required for pull requests?

**To Reproduce**
1. Download the project by git clone project_link
2. Open the project by VS Code on '\zold_wallet' folder then click debug from the menu 
3. Try to run again after adding .vscode folder from any other Flutter project you will see the gradle error.

**Expected behavior**
The project should run once it gets cloned by VS Code and better documentation for the needs and usage of PDD and Docker for contributors.

**Screenshots**
![image](https://user-images.githubusercontent.com/2842459/57894733-3d200d80-7848-11e9-85e1-fadbb79331a9.png)

**Phone (please complete the following information):**
 - Device: Android Emulator API 21
 - OS: Windows 10

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#95](https://github.com/ammaratef45/zold-flutter-client/issues/95) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by ammaratef45** [comment]
@amorenew use the terminal or the command line prompt to build as in [here](https://github.com/ammaratef45/zold-flutter-client/blob/master/README.md#building)

No need to have a .vscode file for this

I've updated the readme and edited the gradle to solve the problems.

No need to know about docker but about pdd you may want to read the [README](https://github.com/yegor256/0pdd) of PDD repository

**Comment by 0crat** [comment]
The job [#95](https://github.com/ammaratef45/zold-flutter-client/issues/95) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/f86dfd36-e60a-47b6-8999-961d2cada868); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by amorenew** [comment]
Project build is working

**Comment by 0crat** [comment]
Job was finished in 15 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#95](https://github.com/ammaratef45/zold-flutter-client/issues/95) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
