### ISSUE TITLE
KeyGap on Emulator

### ISSUE THREAD

**Issue by amorenew** [ammaratef45/zold-flutter-client#96]
**Describe the bug**
I tried to download my Key but I don't know where it is on the emulator
**To Reproduce**
1-Login by mobile number
2-Click download button

**Expected behavior**
A notification to indicate the file is download and I can see the file in the download folder

**Phone (please complete the following information):**
 - Device: Emulator APi 21

**Additional context**
I tried the website of zold but I got a corrupt file while opening it by winrar.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ammaratef45** [comment]
@amorenew This button pulls the wallet, not downloading it..
What do you suggest for us to avoid this conflict next time?

**Comment by 0crat** [comment]
Job [#96](https://github.com/ammaratef45/zold-flutter-client/issues/96) is now in scope, role is `DEV`

**Comment by amorenew** [comment]
@ammaratef45 I didn't know it is a pull button because the icon is similar to the download icon.
I think instead of having progress as bytes it could be just a horizontal spinner with text to indicate the process that happening

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by amorenew** [comment]
@ammaratef45 
1-what is the difference between the key gap and API key "RSA"?
2-and is the app can download the RSA key or it should be from the website

**Comment by ammaratef45** [comment]
@amorenew we can change it from spinner to horizontal, but technically we can't know the progress (only in bytes)
You can check the docs of API for more information about that

**Comment by ammaratef45** [comment]
@amorenew 
>1-what is the difference between the key gap and API key "RSA"?

keygap is a part of the private key (when you lose it you lose your wallet).

API key is a key that is generated by wts, login using your web wallet to get yours

>2-and is the app can download the RSA key or it should be from the website

Currently no, you can submit a ticket for it.

**Comment by amorenew** [comment]
@ammaratef45 You cannot know the total file size?
If so we could do one of the following:
1-Using a circular spinner
2-Assuming that the size is 418 bytes and is fixed.

**Comment by amorenew** [comment]
Choose one of these solutions so we could open a new task for it

**Comment by ammaratef45** [comment]
@amorenew I meant to open a ticket for adding the functionality of downloading the key.

The progress showing issue needs a discussion, if you opened a ticket for it we will have to decide after revising all possible solutions.

**Comment by ammaratef45** [comment]
@amorenew 
>I tried the website of zold but I got a corrupt file while opening it by winrar.

You may open an issue in WTS's repository about that

**Comment by amorenew** [comment]
Ok, when we resolve the other issue we could discuss it again.
Thanks for the help

**Comment by 0crat** [comment]
Job `gh:ammaratef45/zold-flutter-client#96` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#96](https://github.com/ammaratef45/zold-flutter-client/issues/96) is now out of scope
