### ISSUE TITLE
Test Documentation

### ISSUE THREAD

**Issue by amorenew** [ammaratef45/zold-flutter-client#97]
**Is your feature request related to a problem? Please describe.**
I want to run the test but there is not enough documentation on the tests

**Describe the solution you'd like**
1-Test cases need to be cleaner and documented
2-Constant Ids and key used in the test case should be in the Secrets file or in a general constant class
3-The Secrets file should be there with empty value instead of Secrets.dart.asc

**Additional context**
I read PDD docs but I didn't find installation area so how I will use PDD command

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ammaratef45** [comment]
@amorenew [Here](https://github.com/ammaratef45/zold-flutter-client#building) the testing operation is described
You create the secrets file and run the command.

I have no intention for adding an empty file instead of the encrypted one because I want that file (secrets) to be ignored by GIT.

PDD isn't related to testing (It's to check that all todo's in the right format and can be caught and opened as new tickets)
I will edit the docs and include how to install it.

I will leave this issue opened just for the tests documentation part, thanks for mentioning that.

**Comment by amorenew** [comment]
@ammaratef45 
I made a file called secerts.dart as the documentation 
```
class Secrets {
 static const apiKey = '''-----BEGIN PGP MESSAGE-----

hQEMA5qETcGag5w6AQf7BuyfhZj1GUzHZ/qGcYyEAcK3BfB=ajgB
-----END PGP MESSAGE-----''';
}
```

I used my key gap then I used flutter test but I got 6 failed tests.
What I did is right or I missed a step?

**Comment by amorenew** [comment]
what is .asc stand for?

**Comment by ammaratef45** [comment]
@amorenew it's an encrypted file
You're not using wrong APIkey, get your API key from WTS

**Comment by amorenew** [comment]
@ammaratef45 Yes I did use the key gap from wts website but same error.
Note I have 0 zents but this is not the issue if so I will not get 6 fails

**Comment by amorenew** [comment]
@ammaratef45 I think I found the issue
 ` FormatException: Invalid HTTP header field value: "-----BEGIN PGP MESSAGE-----\n\nhQE"`
I got `\n` for spaces because I used `'''text'''`
I wonder how you use your key because with single quotes I need to use escape slash '\' in several places

**Comment by amorenew** [comment]
I installed Ruby and pdd but still the test case I don't know how to set the key in the proper format

**Comment by ammaratef45** [comment]
@amorenew The api key can be found here: https://wts.zold.io/api

it has the following format `ammaratef45-xxxxxxxxx`

**Comment by amorenew** [comment]
@ammaratef45 Yes it is working well thanks
But I got only 2 tests failed.
First:
```
wallet_test.dart: test transactions order [E]
  Expected: not <0>
    Actual: <0>
```
Second:
```
api_test.dart: test API invoice.json [E]
  Expected: '25aXXXXX'
    Actual: 'd9YYYYYY'
```

**Comment by ammaratef45** [comment]
@amorenew Thanks for reporting this

I should fix them

**Comment by 0crat** [comment]
The job [#97](https://github.com/ammaratef45/zold-flutter-client/issues/97) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/335092c1-8275-4e51-9ce1-ec97d83c4097); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)

**Comment by ammaratef45** [comment]
@amorenew can you tell me if tests are good now? what else you think we should have?

**Comment by amorenew** [comment]
@ammaratef45 Yes all tests passed
Thanks

**Comment by 0crat** [comment]
The job [#97](https://github.com/ammaratef45/zold-flutter-client/issues/97) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
