### ISSUE TITLE
UI Tweaks 2

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#99]
Make the following UI changes:

  * Never use background colors. NEVER. Only change the foreground color.

  * The font (size) you have in the login page is not the same as in all other pages. Make sure the font you use there (in the login page) is the one you use everywhere else.

  * The button style you have in the login page (blue) is not the same as the style you use in the "pay" page. Make sure all buttons are blue.

  * Add logo (the same way it is rendered in the login page) to the main screen with transactions.

  * Add title to the "pay" page: "Send ZLD"

  * Add title to the "invoice" page: "Create Invoice"

  * Add more details to the main screen with the list of transactions: 1) how many transactions in the wallet, 2) size of the wallet, 3) taxes (you can find this information in the main page of WTS)

That's it for now.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#99](https://github.com/ammaratef45/zold-flutter-client/issues/99) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#99](https://github.com/ammaratef45/zold-flutter-client/issues/99) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/1d6f40a2-8871-4281-be25-18e9cd8777da); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@yegor256 
>Add more details to the main screen with the list of transactions: 1) how many transactions in the wallet, 2) size of the wallet, 3) taxes (you can find this information in the main page of WTS)

I've opened #104 for this

**Comment by yegor256** [comment]
@ammaratef45 what about page titles?

**Comment by ammaratef45** [comment]
![unnamed](https://user-images.githubusercontent.com/13663221/58475025-208bab80-814d-11e9-912a-52f471d6ae8c.png)

@yegor256 can't see it like this?

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@yegor256 @amorenew I will close this for now

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @amorenew[/z](https://www.0crat.com/u/amorenew), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#99](https://github.com/ammaratef45/zold-flutter-client/issues/99) is not in the agenda of @amorenew[/z](https://www.0crat.com/u/amorenew), can't inspect

**Comment by 0crat** [comment]
The job [#99](https://github.com/ammaratef45/zold-flutter-client/issues/99) is now out of scope

**Comment by sereshqua** [comment]
@ammaratef45 do we consider this task NOT fully completed because of one NOT finished item in Yegor's list? Or would we have another small task to cover that one?

> Add more details to the main screen with the list of transactions: 1) how many transactions in the wallet, 2) size of the wallet, 3) taxes (you can find this information in the main page of WTS)

**Comment by ammaratef45** [comment]
@sereshqua I've added a new ticket for this point, see #104

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @amorenew[/z](https://www.0crat.com/u/amorenew)
